version: '3'

services:
  server:
    image: siegerts/drip
    environment:
      - PLUMBER_DIR=/plumberdir
    ports:
      - 8000:8000
    volumes:
      - ./12-entrypoint:/plumberdir
    restart: always


